name: capture-url
on: deployment_status

jobs:
   capture-url:
    if: github.event.deployment_status.state == 'success' 
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: get branch
      id: get_branch
      run: |
        branch=$(git name-rev --name-only $GITHUB_SHA) 
        echo "preview_branch=$branch" >> $GITHUB_OUTPUT

    - name: get branch test
      id: get_branch_test
      run: |
        branch=${{ github.head_ref }}
        echo $branch

    # - name: replace
    #   uses: mad9000/actions-find-and-replace-string@1
    #   id: findandreplace
    #   with:
    #     source: ${{ steps.get_branch.outputs.preview_branch }}
    #     find: 'remotes/origin/'
    #     replace: '' 

    - name: Replace string
      id: remove-remotes
      uses: frabert/replace-string-action@v2.4
      with:
        pattern: 'remotes/origin/'
        string: ${{ steps.get_branch.outputs.preview_branch }}
        replace-with: 'preview-'

    - name: Handle special characters
      id: handle-especial-chars
      uses: frabert/replace-string-action@v2.4
      with:
        pattern: '/[\~\#\%\&\*\{\}\\\:\<\>\?\/\+\|]/gm'
        string: ${{ steps.remove-remotes.outputs.replaced }}
        replace-with: '-'
 #hello there
  #hello

    - shell: bash
      run: |
       echo ${{ github.event.deployment_status.target_url }} >> ${{ steps.handle-especial-chars.outputs.replaced }}.txt

    - name: Upload url
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.handle-especial-chars.outputs.replaced }}.txt
        path: ${{ steps.handle-especial-chars.outputs.replaced }}.txt

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
 
 
    
