name: capture-url
on: deployment_status

jobs:
   E2E-Tests:
    if: github.event.deployment_status.state == 'success' 
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: get branch
      id: get_branch
      run: |
        branch=$(git name-rev --name-only $GITHUB_SHA) 
        echo "preview_branch=$branch" >> $GITHUB_OUTPUTS

    - shell: bash
      run: |
       echo ${{ github.event.deployment_status.target_url }} > preview_`${{ steps.get_branch.outputs.preview_branch }}`.txt

    - name: Upload url
      uses: actions/upload-artifact@v3
      with:
        name: capture_url
        path: preview_`${{ steps.get_branch.outputs.preview_branch }}`.txt

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
 
 
    
