name: Prod Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:   
    release:
        types: [published]
    workflow_dispatch:
      
jobs:
    build:
        timeout-minutes: 30 # nothing good happens after 30 minutes
        name: Vercel Prod Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'yarn'
                  cache-dependency-path: yarn.lock

            - name: Get node version
              id: node
              run: |
               echo "::set-output name=version::$(node -v)"

            - name: Get node_modules cache
              uses: actions/cache@v3.0.2
              id: node_modules
              with:
                path: |
                    **/node_modules
                key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}

            - name: Install pakages
              run: yarn install --frozen-lockfile --prefer-offline


            - name: Build app
              run: yarn next build

            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}  

            - name: run e2e test
              env:
               BASE_URL: ${{ steps.deploy-vercel-staging.outputs.preview-url }}
               PROD: true
              run: yarn test

