name: E2E Tests
on:
  pull_request:
    types: [labeled]

jobs:
   E2E-Tests-checks:
    timeout-minutes: 30
    if: ${{ github.event.label.name == 'ready' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: get branch
      id: get_branch
      run: |
        branch=${{ github.head_ref }}
        echo "preview_branch=$branch" >> $GITHUB_OUTPUT

    - name: Handle special characters
      id: normalize_URL
      uses: frabert/replace-string-action@v2.4
      with:
        string: ${{ steps.get_branch.outputs.preview_branch }}
        pattern: '[\~\#\%\&\*\{\}\\\:\<\>\?\/\+\|]'
        replace-with: '-'
        flags: 'g'

    - name: Download URL file
      uses: dawidd6/action-download-artifact@v2.26.0
      with:
        workflow: capture_url.yml
        name: preview-${{ steps.normalize_URL.outputs.replaced }}.txt
        search_artifacts: true    

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Store preview URL
      id: capture-url
      shell: bash
      run: |
        previewURL=`cat preview-${{ steps.get_branch.outputs.preview_branch }}.txt`
        echo "preview_url=$previewURL" >> $GITHUB_OUTPUT 
    
    - name: Install playwright
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: yarn add @playwright/test

    - name: Install playwright deps
      run: npx playwright install --with-deps chromium

    - name: Run Playwright tests
      env: 
        BASE_URL: ${{ steps.capture-url.outputs.preview_url }}
      run: yarn test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 3    
 
 
    
