name: E2E Tests
on:
  pull_request:
    types: [labeled]

jobs:
   E2E-Tests:
    timeout-minutes: 30
    if: ${{ github.event.label.name == 'ready' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    # - shell: bash
    #   run: |
    #    echo ${{ github.event.deployment_status.target_url }} > preview_url.txt
    # - name: Upload url
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: capture_url
    #     path: preview_url.txt

    # - name: Upload math result for job 2
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: capture_url
    #     path: preview_url.txt

    - name: Download workflow artifact
      uses: dawidd6/action-download-artifact@v2.26.0
      with:
        workflow: capture_urls.yml
        name: capture_url
    - name: Print the final result
      id: capture-url
      shell: bash
      run: |
        value=`cat preview_url.txt`
        echo $value >> $GITHUB_OUTPUT 
        
    
    - name: Install pakages
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: yarn

    - name: Install Playwright 
      run: npx playwright install --with-deps chromium

    - name: Run Playwright tests
      env: 
        BASE_URL: ${{ steps.capture-url.outputs.preview_url }}
      run: yarn playwright test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 3    
 
 
    
