name: E2E Tests
on:
  pull_request:
    types: [labeled]

jobs:
   Tests-E2E:
    timeout-minutes: 30
    if: ${{ github.event.label.name == 'ready' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: get branch
      id: get_branch
      run: |
        branch=${{ github.head_ref }}
        echo "preview_branch=$branch" >> $GITHUB_OUTPUT

    - name: Handle special characters
      id: file_name
      uses: frabert/replace-string-action@v2.4
      with:
        string: ${{ steps.get_branch.outputs.preview_branch }}
        pattern: '[\~\#\%\&\*\{\}\\\:\<\>\?\/\+\|]'
        replace-with: '-'
        flags: 'g'

    - name: Download URL file
      uses: dawidd6/action-download-artifact@v2.26.0
      with:
        workflow: capture_url.yml
        name: preview-${{ steps.file_name.outputs.replaced }}.txt
        search_artifacts: true

    - name: Store preview URL
      id: capture-url
      shell: bash
      run: |
        previewURL=`cat preview-${{ steps.file_name.outputs.replaced }}.txt`
        echo "preview_url=$previewURL" >> $GITHUB_OUTPUT


    - uses: actions/cache@v2
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}

    - name: Install playwright
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: yarn add @playwright/test
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
      if: steps.playwright-cache.outputs.cache-hit != 'true'
    - run: npx playwright install-deps
      if: steps.playwright-cache.outputs.cache-hit == 'true'  
    
    - name: Run Playwright tests
      env: 
        CI: true
        TEST_ACCOUNT_EMAIL: ${{ secrets.TEST_ACCOUNT_EMAIL }}
        TEST_ACCOUNT_PASS: ${{ secrets.TEST_ACCOUNT_PASS }}
        EMPTY_TEST_ACCOUNT_EMAIL: ${{ secrets.EMPTY_TEST_ACCOUNT_EMAIL }}
        EMPTY_TEST_ACCOUNT_PASS: ${{ secrets.EMPTY_TEST_ACCOUNT_PASS }} 
        BASE_URL: ${{ steps.capture-url.outputs.preview_url }}
      run: yarn test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 3   
 
 
    
