name: Playwright Tests
on: [pull_request, deployment, deployment_status, workflow_dispatch]
jobs:
# test push
   run-e2es:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Cache node_modules
      uses: actions/cache@v3
      id: cache-node-modules
      with:
          path: |
              node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install pakages
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: yarn

    - name: Install Playwright 
      run: npx playwright install --with-deps chromium

    - name: Run Playwright tests
      run: yarn playwright test
