on:
  release:
    types: [published]
    branched: 'release-deployments'
### hello
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: curl -X POST -d {} https://api.vercel.com/v1/integrations/deploy/prj_kxsc3DGbUTuntoxpgxwmQh90Re2P/LGlvI9oSCE
